controllers/PerspageController.php
<?php

namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

use app\models\art\Map_coords;
use app\models\art\Interests;
use app\models\art\Project;
use app\models\art\Userinfo;
use app\models\art\Friends;
use app\models\art\Events;
use app\models\art\Message;
use app\models\art\Category;
use app\models\art\User;
use app\models\art\Likes;
use app\models\art\Comments;
use app\models\art\Categ_projects;
use app\models\art\News;
use app\models\art\Bookmarks;
use app\models\art\Subscribers;
use app\components\Test;
use app\components\Websocket;
use app\components\socketClient;

class PerspageController extends Controller{
    
    public $arr=[];
    public $layout = 'personalpage';    
    public $user_projects_arr=[];


    public function actionIndex(){
 
        return $this->render('index');
   }
   
    public function actionBookmarks(){
        $user_id=Yii::$app->user->getid();
        $bookmarks=new Bookmarks;
        $likes=new Likes;
        $subscribers=new Subscribers;
        $bookmark=$bookmarks->getbookmarksfromuser($user_id);

        $like=$likes->getuserlikes($user_id);
        $subscriber=$subscribers->getuser_subscribers($user_id);

        return $this->render('bookmarks',['bookmarks'=>$bookmark,'likes'=>$like,'subscribers'=>$subscriber]);
   }
   
    public function actionStatistic(){

        return $this->render('statistic');
    }

    protected function getuserid($nickname){
        
         $user=new User;
            $user_id=$user->find_id_nickname($nickname);
            return $user_id;
    }


    public function actionMessagelist(){
        $user_id=Yii::$app->user->getid();
        $request_nick=Yii::$app->request->get('nick');
        $request_user_id=$this->getuserid($request_nick);
            if ($user_id === $request_user_id ){
                $message= new Message;
                $rez=$message->getmessagelist($user_id);
        
                return $this->render('messages',['messagelist'=>$rez]);
            }else{
                return $this->render('error',['error'=>'Доступ к данному разделу закрыт']);


            }

    }

       public function get_cur_proj_cat($proj_id){
                $categ_project=  new Categ_projects;
            
                $category_rez=$categ_project->get_cat($proj_id);
                return      $category_rez;
        }
        
        
    public function actionChartsdata(){
                $usercateg=[];
                $incremet=0;
            $colors=[ '#C9BAA1', '#D38C7C', '#7FBBC4','#9C9CBA','#CCA9C6','#998B96'];
            $color_length=sizeof($colors);
            $user_id=Yii::$app->user->getid();
            $obj=new Category;
            $count_proj=$obj->count_proj($user_id);

             $count_categ=$obj->view_categ_charts($user_id);

                foreach( $count_categ['user_categ'] as $key){
                   $usercateg[$key['name']]=$key['count'];

                }


            /*заполняем массив данными по катеорям*/
                    foreach($count_categ['all_categ'] as $key){     
                        $count= array_key_exists($key['name'],$usercateg) ? $usercateg[$key['name']]: 0;
                             $this->arr[]['c']= 

                                    [
                                        ["v"=>$key['name'],"f"=>null],
                                        ["v"=>$count,"f"=>null],
                                        ["v"=>   "fill-color:". $colors[$incremet].";stroke-color: grey; stroke-width: 1","f"=>null]
                                     ];

                              $incremet == $color_length-1 ? $incremet = 0 : $incremet++;;
                        } 

                $json_chart_data['colls'] = [
                     "cols"=> [
                             ["id"=>"","label"=>"Проектов ","pattern"=>"","type"=>"string"],
                              ["id"=>"","label"=>"Проектов ","pattern"=>"","type"=>"number"],
                              ["type"=>"string","role"=>"style"]
                    ],

                    "rows"=>  $this->arr
                ];


                $json_chart_data['pie'] = [
                    "cols"=> [
                          ["id"=>"","label"=>"Topping","pattern"=>"","type"=>"string"],
                          ["id"=>"","label"=>"Проекты","pattern"=>"","type"=>"number"]
                        ],
                    "rows"=>[
                        ["c"=>[["v"=>null,"f"=>'Активные'],["v"=>$count_proj['active'],"f"=>$count_proj['active']],]],
                        ["c"=>[["v"=>null,"f"=>'Неактивные'],["v"=>$count_proj['noactive'],"f"=>$count_proj['noactive']],]],

                    ]
               ];


                $json_chart_data['max_count_categ']= $count_categ['max_count']['count'];


                return  json_encode($json_chart_data) ;



    }
    public function actionGetproj($proj){


           $project= new Project;
                    $rez= $project->get_project_files($proj);
                    return $this->render('project',['project'=>$rez]);


    }

    public function actionGetuserpage($id){

       return $this->render('index');

    }

    public function actionSetmessage(){
        if(Yii::$app->request->post('setmessage')){
            $time_zone=new Map_coords;
            /*my time_zone*/
            $timezone_user=$time_zone->get_time_zone(Yii::$app->user->getid());
            if (sizeof( $timezone_user) == 0){  $timezone_user = 'Europe/Moscow';}
            $date_user_zone = new \DateTime('now', new \DateTimeZone($timezone_user));
            $user_date= $date_user_zone ->format('Y-m-d H:i:s');

            $user_id=Yii::$app->user->getid();
            $friend_id=Yii::$app->request->post('friend_id');
            $text_message=Yii::$app->request->post('setmessage');
            $message_id=Yii::$app->request->post('message_id');

            /*friend_time_zone*/

            $timezone_friend=$time_zone->get_time_zone($friend_id);
                if (sizeof(  $timezone_friend) == 0){   $timezone_friend = 'Europe/Moscow';}
            $date_friend_zone = new \DateTime('now', new \DateTimeZone($timezone_friend));
            $friend_date= $date_friend_zone->format('Y-m-d H:i:s');
    //        return $friend_date;

            /*send mess*/
            $setmessage= new Message();
            $setmessage->insertMessage($user_id,$friend_id,$text_message,$user_date,$friend_date,$message_id);

            $all_date=$user_date."#".$friend_date;
            /*return user_date*/

            return (string)$all_date;
        }

    }

    public function actionGetmessage(){
            $user_id=Yii::$app->user->getid();
            $friend_nickname=Yii::$app->request->get('friend_nick');
            $friend_id=$this->getuserid($friend_nickname);
            $message=new Message();
            $rez=$message->getmessages($user_id,$friend_id);

            $jsonarr=[];
            $messarr=[];



            foreach ($rez['mes'] as $key){

                $messarr[$key['id']]['date']=$key['date'];
                $messarr[$key['id']]['text']=$key['text'];
                $messarr[$key['id']]['ava']=$key['ava'];
                 $messarr[$key['id']]['nickname']=$key['nickname'];

            }
             $jsonarr['message_info']['friend_nickname']=  $friend_nickname;
             $jsonarr['message_info']['friend_id']=  $friend_id;
             $jsonarr['message_info']['messages']=  $messarr;
          return  Yii::$app->request->isAjax ? json_encode($jsonarr): $this->render('showmessage',['messarr'=>$jsonarr['message_info']]);



    }



   static function cmp($a, $b) 
{
   
    if ($a['date'] == $b['date']) {
        return 0;
    }
    return ($a['date'] < $b['date']) ? -1 : 1;

}

    
    public function actionShow_noviewed_events(){
        $jsonarr=[];
        $user_id=Yii::$app->user->getid();
        $event=new Events();
        $message=$event->show_all_events($user_id);

    //      foreach($message as $key){
    //          $key['date'];
    //          $jsonarr[]['data']=$key['date'];
    //      }


    /*sort array to date*/
    usort($message, array($this,"cmp"));
    $json_arr['allevents']=$message;


    return json_encode($json_arr) ;
    }




    public function actionAddfriend(){


        $user_id=Yii::$app->user->getid();
        $friend_id=$this->getuserid(Yii::$app->request->post('friend_nick'));
      

        /*get time_zone*/
        $time_zone=new Map_coords;


                /*friend_time_zone*/
        $timezone_user=$time_zone->get_time_zone($friend_id);
         if (sizeof( $timezone_user) == 0){  $timezone_user = 'Europe/Moscow';}
        $date_friend_zone = new \DateTime('now', new \DateTimeZone($timezone_user));
            /*friend_date*/
        $friend_date=$date_friend_zone ->format('Y-m-d H:i:s');


        $friends=new Friends();

        $addfriend=$friends->setfriend($user_id,$friend_id,$friend_date);




        if(!$addfriend ){return '0';}else{

        }


    }

    public function actionFriendslist(){
                $arr=[];
                $user_id=Yii::$app->user->getid();
                $friends=new Friends();
                $friends=$friends->getfriends($user_id);
                return json_encode( $friends);
    }
    public function actionFriends(){


            if(Yii::$app->request->isGet){
                     return $this->render('friendlist');

            }



    }
    public function actionNews(){
            $user_id=Yii::$app->user->getid();
            $news=new News();
            $project=new Project();
            $comments=new Comments();
            $likes=new Likes();
            $newsarr=$news->getnews($user_id);
            $rez['news']=[];

        forEach($newsarr as $key){

            if ($key['project_id'] != null){

                 $project_rez=$project->getproject_for_news($key['project_id']);
                 $project_rez['text']='добавил новый проект';

views/perspage/bookmarks.php
<?php
$this->title='Ваши закладки';
$this->params['breadcrumb'][] =$this->title;
?>

<script>
    document.querySelector('.user_bookmarks').parentNode.classList.add('user_menu_div_click');

</script>

<div class="project_header_top">
    
    <div>
           <div class="items_nav" >
                   <span class="bookmark_peoples active ">Люди</span>
                         
                       <span class="bookmark_projects"> Проекты</span>
        
   
                      <span class="bookmark_likes"> Что вам понравилось  </span>
                
            </div>
    </div>
</div>

<div id="bookmarks" class="container_content">
   
           



               <div class="bookmark_peoples_content show">
                     <?php if(sizeof($subscribers) > 0){
                         
                         foreach($subscribers as $key){?> 
                     <div class="bookmarks_peoples_item_wrap">
                           <div class="peoples_item">
                               <div class="peoples_item_ava" style=" background:url(<?php echo $key['ava']?> ) center/contain no-repeat;">

                               </div>
                               <p><?php echo $key['nickname']?></p>
                           </div>
                     </div>
                             
                         <?php } ?>
                          
                    <?php }?>
               </div>
               
                <div class="bookmark_projects_content">
                      <?php if (sizeof($bookmarks) >0){
                          foreach($bookmarks as $key){?>     
                      <div class="bookmarks_bookmarks_item_wrap">
                                   <div class="bookmarks_bookmark_item ">
                                       <div style=" background:url(<?php echo $key['ava']?> ) center/cover no-repeat;"class='bookmark_project_foto'>
                                           
                                       </div>
         
                                <p class='bookmark_project_name'><?php echo $key['name']?></p>
                           
                                      
                                   </div>
                                   
                               
                                   <div class="bookmark_author">
                                         <p><?php echo $key['nickname']?></p>
                                         <p><img width='65%' src="<?php echo $key['userava'];?>" /></p>
                                   </div>
                             </div>

                       <?php }  ?>    <?php }  ?>
                          
        
               </div>
               
                <div class="bookmark_likes_content">
                                            <?php if (sizeof($likes) >0){
                          foreach($likes as $key){?>     
                               <div class="bookmarks_bookmarks_item_wrap">
                                   <div class="bookmarks_bookmark_item ">
                                       <div style=" background:url(<?php echo $key['ava']?> ) center/cover no-repeat;"class='bookmark_project_foto'>
                                           
                                       </div>
         
                                <p class='bookmark_project_name'><?php echo $key['name']?></p>
                           
                                      
                                   </div>
                                   
                               
                                   <div class="bookmark_author">
                                         <p><?php echo $key['nickname']?></p>
                                         <p><img width='65%' src="<?php echo $key['userava'];?>" /></p>
                                   </div>
                             </div>

                       <?php }  ?>    <?php }  ?>
                          
               </div>
 
    

    
</div>

views/perspage/error.php
<div class=' col-md-3 col-md-push-4 error_access'>
    <?php echo $error;?>
</div>

views/perspage/friendlist.php
<?php
$this->title='Ваши друзья';



$this->params['breadcrumb'][] =$this->title;


?>

<script>
    document.addEventListener("DOMContentLoaded",function(){
    document.querySelector('.user_friends').parentNode.classList.add('user_menu_div_click');


    })
       
</script>

<div class="project_header_top_adaptive ">
    
    <div>

         <div data-length='3' class='items_nav hide'>
              <span class="added_friends_all active">Все</span>
      <span class="added_lately_list">Недавно добавленные</span>
             <span class="accept_friend_show">Запросы на добавление</span>          
             <span class="request_friend_show">Ваши запросы</span>
         </div>
    </div>
</div>
 
        
<div class='container_content ' id="friendlist">
              <p class='friend_list_request_nav  input_nav'>
            <input  type="search" placeholder='Введите имя друга' />
         </p>

        <div id='friend_list_accept' class='col-xs-12 show'>
                
        </div>
       

        <div class='added_lately_friend_list col-xs-12 ' >

        </div>
        <div class='accept_friend_list col-xs-12'>


        </div>

        <div class='request_friend_list col-xs-12'>


        </div>

 </div>
    

<script>

    function getAjax(){
          var xmlhttp;
          try {
            xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
          } catch (e) {
            try {
              xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            } catch (E) {
              xmlhttp = false;
            }
          }
          if (!xmlhttp && typeof XMLHttpRequest!='undefined') {
            xmlhttp = new XMLHttpRequest();
          }
          return xmlhttp;
}

var httpRequest=getAjax();
  var url='/perspage/friendslist',
  friend_request_to_me='',
  current_friends='',
  request_friend='',
  lately_friend='';

httpRequest.onreadystatechange=function(){
     
      if (httpRequest.status == 200 && httpRequest.readyState ==4) {
                  
                var data= JSON.parse(httpRequest.responseText);
                var accept_data=data['accept_friends'];
                var request_data=data['request_friends'];
                var lately_friends=data['lately']
                var accept_data_length=accept_data.length;
                var request_data_length=request_data.length;

                
                if(accept_data_length>0){
                    for(var i=0;i<accept_data_length;i++){

                        if(accept_data[i]['submit_friend']=='0'){
                            friend_request_to_me+='<div class="peoples_item"><div class="peoples_item_ava" style=" background:url('+ accept_data[i]["ava"]+') center/contain no-repeat"> </div> <p><a target="_blank" href="/users/'+accept_data[i]['nickname']+'">'+accept_data[i]['nickname']+'</a></p><p><span class="accept_friend glyphicon glyphicon-ok"></span><span class="cancel_friend glyphicon glyphicon-remove"></span></p></div>';

                        }
                        else{

                            current_friends+='<div class="peoples_item"><div class="peoples_item_ava" style=" background:url('+ accept_data[i]["ava"]+') center/contain no-repeat"> </div> <p><a  class="curent_friend_nick" target="_blank" href="/users/'+accept_data[i]['nickname']+'">'+accept_data[i]['nickname']+'</a></p></div>';
                        }

                    }
                 }
            
                 if(request_data_length>0){
                    for(var i=0;i<request_data_length;i++){

                        if(request_data[i]['submit_friend']=='0'){
      
                            request_friend+= '<div class="peoples_item"><div class="peoples_item_ava" style=" background:url('+ request_data[i]["ava"]+') center/contain no-repeat"> </div> <p><a target="_blank" href="/users/'+request_data[i]["nickname"]+'">'+request_data[i]["nickname"]+'</a></p></div>';
                        }

                      
                        else{
                           
                                                       current_friends+='<div class="peoples_item"><div class="peoples_item_ava" style=" background:url('+ request_data[i]["ava"]+') center/contain no-repeat"> </div> <p><a class="curent_friend_nick"  target="_blank" href="/users/'+request_data[i]["nickname"]+'">'+request_data[i]["nickname"]+'</a></p></div>';
                        }

                    }
                 }
                 
                 if(lately_friends.length>0){
                    var length=lately_friends.length
                    for(var i=0;i<length;i++){
                
                           lately_friend+='<div class="peoples_item"><div class="peoples_item_ava" style=" background:url('+ lately_friends[i]["ava"]+') center/contain no-repeat"> </div> <p><a target="_blank" href="/users/'+lately_friends[i]["nickname"]+'">'+lately_friends[i]["nickname"]+'</a></p></div>';
                        }

                 }
        }
        
       
    }
    
    
    
    
    

httpRequest.open('GET',url,true);
httpRequest.send();

window.onload=function(){
//var list=document.querySelectorAll('.friends_lists_main>div');
//
//Array.prototype.forEach.call(list,function(el,i){
//    
//    el.addEventListener('click',function(e){
//        var target=e.target;
//        while(!target.classList.contains('friend_div')){
//          target=target.parentNode;
//        }
//        if(target ){
//            var friend_nick=target.getAttribute('data-friend-nickname');
//
//            location.href='/users/'+friend_nick
//
//
//        }
//
//    })
//})
//        
                

    document.querySelector('.accept_friend_list').innerHTML=friend_request_to_me;
    document.querySelector('.request_friend_list ').innerHTML=request_friend;
    document.getElementById('friend_list_accept').innerHTML=current_friends;
    
    document.querySelector('.added_lately_friend_list').innerHTML=lately_friend;
          
      

}

</script>

views/perspage/friendpage.php
<?php
use app\assets\Settings;
$this->title='Личная страница '.$nick;
$this->params['breadcrumb'][] =$this->title;
$this->registerJsFile('http://maps.googleapis.com/maps/api/js?key=AIzaSyDCwmNsO67x5VPyYEKfTEGUHU--6AfVtyQ&libraries=places',['position'=>Yii\web\View::POS_END,'depends' =>'yii\web\YiiAsset']);
$this->registerJsFile(Yii::$app->request->baseUrl.'/js/googlemap.js',['depends' => '\app\assets\SecAsset']); 
Settings::register($this);
?>

<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet"> 
<style>
    .label{font-size:0.9em;}
    .bootstrap-tagsinput{text-align:left;}
</style>


<div id='user_page' data-user-nick="<?php echo $nick;?>" class=" clear col-xs-12">
 

    <div <?php if($userinfo_arr['background'] != NULL){ ?> data-background-path="<?php echo  $userinfo_arr['background'];?>" style="background:url(<?php echo  $userinfo_arr['background'];?>)  center/cover"<?php } ?> class="user_profile_header<?php if($userinfo_arr['background'] == NULL){ ?> user_profile_fon <?php } ?>">
        
        
        <?php if($owner){?>
        
        <p class="  edit_userpage_fon "><span class="glyphicon glyphicon-picture"></span>Изменить фон <input type='file' class='edit_userpage_fon_input' /></p>
            <p class="reset_userpage_fon"><span class="glyphicon glyphicon-picture"></span>Сбросить фон</p>
                   <p id="edit_user_info"><span class="glyphicon glyphicon-edit"> Редактировать информацию</span></p>
            
        <?php }else{
           
            if($friend_status==1){  $message_par='Удалить из друзей';
                
            }else if($friend_status==0) {$message_par='';}
            else{ $message_par='Добавить в друзья';}?>
              <p id="userpage_nav"><span data-user-id="<?php echo $owneruserid;?>" class=" open_message_area"> Написать сообщение</span><span data-user-id="<?php echo $owneruserid;?>" data-friend-status="<?php echo  $friend_status ?>" class="user_add_friend"><?php echo $message_par ;?></span><span data-user-page-nick='<?php  echo $nick;?>' class="subscribe">Подписаться</span></p>
       <?php }?>
 
    
                
        <div class="userpage_foto">
     
                 <p class='user_nickname' data-user-id='<?php echo $owneruserid;?>'><?php echo $nick?></p>
                    <div class="user_profile_ava cropfoto_area">

                        <img  alt="" src="<?php echo $userinfo_arr['ava'];?>"/>

                    </div>
       </div>
        <div class='addfriend_mess_wrap'>

        </div>
    
     </div>
<div class="user_info col-xs-12">
    <div class='userpage_menu_wrap'>
<div class="project_header_top_adaptive_userpage userpage_menu" >
    
    <div>
           <div class="items_nav">
                   <span class="perpage_info active ">Личная информация</span>
                         
                       <span class="perspage_projects"> Проекты</span>
        
   
  
                
            </div>
    </div>
</div>
    </div>
     
     <div class="profile_content_wrap container_content_menu ">
     
               <div class='user_profile_all_informaton_wrap hide show' >
                <!--this div is hide. show only when edit pers info-->
      
                    
                 
                   <div class="personalinfo">
                           <h4> Личная информация</h4>
                       <?php 
                     
                       if(sizeof($userinfo_arr)>0){ 
                           
                 
                           $item='';
                          
                           ?>
                
               
                      
                       
             <div class='input_user_info '>
                    
<?php 

foreach($userinfo_arr as $key=>$value){
    
       switch ($key){

           case 'name':
                $item='Имя';$inputtype='text'; break;
           case 'surname':
                $item='Фамилия';$inputtype='text'; break;
           case 'age':
                $item='возраст';
                $inputtype='text';break;
           case 'website':
                $item='Сайт';$inputtype='url'; break;
           case 'email':
                $item='Email'; $inputtype='email';break;

           default:  $item='';
       }
       
      
       
             if( $item !='')  {?>   
                                          <div class=" col-xs-12 input-group user-setting_input">
                                                       <div class="noedit_userinfo_symv noedit_userinfo input-group-addon" ><?php echo $item;?> </div>
                                                       <input disabled name='user-<?php echo $key?>'  value="<?php echo $value ?>" type="<?php echo $inputtype; ?>" id="user_<?php echo $key?>" class=" noedit_userinfo  form-control" aria-describedby="basic-addon2">
                                         </div>
                       

            <?php }


     } ?>

                        </div>
                          <?php   }?>
                           
                          
                 
                   </div>  
                 
                   <div class="interests">
                           <h4> Интересы</h4>
                           
                         <div class='interes_div '>
                                <p class="hideinteres_input interes_hide">Ваши интересы (введите текст и нажмите Enter)</p>

                            <div class="interes_val">
                              
                                <?php 

                                if(sizeof($interests)>0){
         
                                   foreach($interests as $key){

                                       ?> <span data-tag-id = "<?php echo  $key['id'];?>"  class="tag label label-info pers_page_interes"><?php echo $key['interes_val'] ?><span class="hideinteres_input_inline removetag" data-role="remove"></span></span><?php
                                   }

                                }else{ ?> <p class='noinfo'>Информация не найдена</p> <?php }?>
                          
             
                           </div>        

                                <p  value=''  class="hideinteres_input form-control" ></p>
                        </div>
                           
                           
                   </div>
                   <div class="location ">
                       <h4> Локация</h4>
                       
   <p class='hide_location_input'>Укажите ваш город</p>

   <p class='hide_location_input'><input  id="user_city" type="text" /> </p>
      
                       
                        <?php if (sizeof($location) > 0){?>

                           <p class="perspage_city_name"><?php echo $location['location']?></p>
                            <div  class='col-xs-12 map_wrap' >    
                                 <span class="hidden lat_val" ><?php echo $location['lat']?></span> <span class="hidden lng_val" ><?php echo $location['lng']?></span><span class="hidden" id="location_val" ></span>
                              <div id="map-canvas"></div>
                            </div>


                        <?php } else{ ?>
                        <p>Информация не найдена</p><?php }?>
                      
                   </div>

     
                </div>
 
                <div class='user_profile_projects_wrap col-xs-12 hide '>
          
                    <div class='userpage_projects clear'>
                        <div id='project_list' class="projects"></div>
                
            
                    </div>
                </div>
         
</div>
    <div class='hide mybtn btn_bottom_right cancel_user_info'>
               Закрыть
                </div>
<div class='hide mybtn btn_bottom_right save_user_info'>
               Сохранить
                </div>
</div>
          
        </div>

views/perspage/messages.php
<script>
    document.addEventListener("DOMContentLoaded",function(){
    document.querySelector('.user_messages').parentNode.classList.add('user_menu_div_click');
    })
</script>

<?php

$this->title='Сообщения';
$this->params['breadcrumb'][] =  $this->title;?>     

    <div class="message_peoples_list_wrap container_content">
    <div>
                <div class="search_message">
            <input type="search" placeholder=" "/>
        </div>
    </div>
    <div class='message_peoples_list '>

        
        <?php if (sizeof($messagelist) >0 ){
           
            
            foreach($messagelist as $key=>$value){
                ?>

            
     
                           
                    <div class='col-xs-12 message_list_div' data_friend_nick='<?php echo $value['nickname'];?>'>
                    
                        <div class='message_owner'>
                            <p class ='message_block_nick'><?php  echo  $value['nickname']?></p>
                            <img width='60px' alt='фото' src='<?php echo  $value['ava'] ;?>' />
                        </div>
                      
                        <div class='message_datetime'>
                            <p><?php echo  $value['date'] ?></p>
                        </div>
                          <div class='message_text message_block_text'>
                            <p><?php echo  $value['text'] ;?></p>
                        </div>
                        
                    </div>
       
            <?php } ?>
        <?php } ?>
                
    </div>
</div>
              
            
            
     

    

views/perspage/showmessage.php
<style>
    .message_box{display:block;}
</style>      
                            <div class="message_box">
    <p class="close_window close_message open_message_list">Закрыть</p>
  
    <?php $nickname=$messarr['friend_nickname'];?>

    <div class="message_header">
        <p class="message_friend_name" style="text-align:left;margin-left:20px;"><?php echo $nickname;?></p>
    </div>
           

    <div class="message_body_wrap col-xs-12">
        <div class="message_body col-xs-12"> 
           <?php foreach($messarr['messages'] as $key){
            $date=$key['date'];
            $time_date=explode(' ',$date);
            $date=$time_date[0];
            $time=explode(':',$time_date[1]); ?>
                  <div class='message_wrap col-xs-12'><div class='message_owner col-xs-2'><p><?php echo $key['nickname']?></p><img style='width:90%' src='<?php echo $key['ava'];?>'/></div><div class='col-xs-8 message_text'><?php echo $key['text'];?>
                           </div><div class=' col-xs-2 message_datetime'><?php echo $date.'<br/>'.$time[0].':'.$time[1]; ?></div></div>

                  
              <?php } ?>

        </div>
    </div>
    <div class="message_input_area_wrap">
        <textarea class="message_input_area"></textarea>
    </div>
    <div class="send_message_wrap">
         <p class="send_message">Отправить</p>
    </div>
</div>
              
              

views/perspage/userinfo.php
        <?php 
        $this->title='Личный кабинет';
        
        $this->params['breadcrumbs'][] = $this->title;  ?>                                                       





    
         


   
 

                  
        
 